apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::311638606192:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1F6I3T17ABUMM
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::311638606192:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-12-01T10:04:06Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1402"
  uid: 6bd18c2b-8a41-4265-8df8-4c189b078986
